branch-defaults:
  master:
    environment: bio-scenarios-figure-dev
    group_suffix: null
  validation-edits:
    environment: bio-scenarios-figure-dev
environment-defaults:
  bio-scenarios-figure-dev:
    branch: null
    repository: null
global:
  application_name: bio-scenarios-figure
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
